version: 0.2

phases:
  pre_build:
    commands:
    - echo "pre_build"
  build:
    commands:
    - terraform init
    - terraform apply -auto-approve
  post_build:
    commands:
    - echo "post_build"
