variable "github_token_ssm_key" {}
variable "codebuild_role_name" {}
variable "codebuild_name" {}
variable "buildspec_file_name" {}
variable "terraform_image_tag" {}
variable "codepipeline_role_name" {}
variable "artifact_bucket_name" {}
variable "codepipeline_name" {}
variable "repository_name" {}
variable "repository_owner" {}
variable "github_event" {}
variable "webhook_jsonpath" {}
variable "webhook_match_equal" {}